name: Linting

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch: {}

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16

      - name: Install dependencies
        run: |
          pip install pylint
          REQUIREMENTS_FILES=$(find . -name "requirements.txt")
          for file in $REQUIREMENTS_FILES; do
            directory=$(dirname $file)
            pip install -r $file
          done

      - name: Run pylint on Python files
        run: |
          files=$(find . -type f -name '*.py' -not -path './.git/*')
          for file in $files; do
            pylint --fail-under=8 $file
          done
