name: Testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch: {}

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16

      - name: Install dependencies
        run: |
          pip install pytest
          REQUIREMENTS_FILES=$(find . -name "requirements.txt")
          for file in $REQUIREMENTS_FILES; do
            directory=$(dirname $file)
            pip install -r $file
          done

      - name: Run pytest
        run: |
          pytest -v -s $(find . -name "*_test.py")
